{
    'name': 'AK Tripletex Authentication',
    'version': "18.0.1.0.0",
    'summary': """Odoo and Tripletex integration""",
    'author': "Hundred Solutions",
    'maintainer': 'Hundred Solutions',
    'company': "Hundred Solutions",
    'website': 'https://www.hundredsolutions.com/',
    'category': 'Industries',
    'description': """
    Helps You To work odoo and tripletex.
    """,
    'depends': [
        'base',
        'hr',
        'contacts',
        'mail',
        'stock',
        'sale_management',
        'account',
        'purchase'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/uom_common_code_views.xml',
        'report/invoice_template_inherit.xml',
        'views/product_template_views.xml',
        'views/account_move_reversal_wizard_views.xml',
        'views/account_move_views.xml',
        'views/account_tax_views.xml',
        'views/res_config_settings.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/product_uom_views.xml',
        'wizard/session_token_wizard_views.xml',
        'views/tripletex_session_token_views.xml',
        # 'views/tripletex_customer_data_views.xml',
        'wizard/tripletex_product_sync_views.xml',
        'wizard/tripletex_customer_sync_views.xml',
        'wizard/tripletex_supplier_sync_views.xml',
        'wizard/menuitems.xml',
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
}
